<a href="https://colab.research.google.com/github/moriuchi-lab/-Prog2kakushin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpyを用いる

ビンゴ大会

ビンゴで遊べるプログラムを作りました

In [2]:
import numpy as np
import random

時間がないけど遊びたい人用

In [60]:
N=5
a=np.random.randint(1,41,(N,N))
b=np.random.randint(1,41,(N,N))
print('card A')
print(a)
print('card B')
print(b)
x=str(input('AとBどちらのカードにしますか? '))
count=0
while count!=-1:
  count+=1
  atari=np.random.randint(1,41)
  print(str(count)+'番目に出た数字は '+str(atari))
  a_new=np.where(a==atari,0,a)
  b_new=np.where(b==atari,0,b)
  a=a_new
  b=b_new
  print('card A')
  print(a_new)
  print('card B')
  print(b_new)
  c=np.sum(a_new,axis=0)
  d=np.sum(a_new,axis=1)
  e=np.sum(b_new,axis=0)
  f=np.sum(b_new,axis=1)
  g=np.diag(a_new)
  h=np.diag(np.fliplr(a_new))
  j=np.diag(a_new)
  k=np.diag(np.fliplr(a_new))
  for i in range(N):
    if c[i]==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    elif d[i]==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    elif np.sum(g)==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    elif np.sum(h)==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    if e[i]==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break
    elif f[i]==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break
    elif np.sum(j)==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break
    elif np.sum(k)==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break

if x==y:
  print('あなたの勝ちです')
else :
  print('あなたの負けです')

card A
[[ 2 16 36 12 15]
 [16 39 15 25 10]
 [ 9 36 12 39 26]
 [ 5 26 22 26 11]
 [ 3 14 25 35 12]]
card B
[[12 37  8 32  8]
 [29 22  1 31 13]
 [33 14 19 19 22]
 [ 9 19  8 23 36]
 [ 5  8 39 22 39]]
AとBどちらのカードにしますか? A
1番目に出た数字は 10
card A
[[ 2 16 36 12 15]
 [16 39 15 25  0]
 [ 9 36 12 39 26]
 [ 5 26 22 26 11]
 [ 3 14 25 35 12]]
card B
[[12 37  8 32  8]
 [29 22  1 31 13]
 [33 14 19 19 22]
 [ 9 19  8 23 36]
 [ 5  8 39 22 39]]
2番目に出た数字は 24
card A
[[ 2 16 36 12 15]
 [16 39 15 25  0]
 [ 9 36 12 39 26]
 [ 5 26 22 26 11]
 [ 3 14 25 35 12]]
card B
[[12 37  8 32  8]
 [29 22  1 31 13]
 [33 14 19 19 22]
 [ 9 19  8 23 36]
 [ 5  8 39 22 39]]
3番目に出た数字は 21
card A
[[ 2 16 36 12 15]
 [16 39 15 25  0]
 [ 9 36 12 39 26]
 [ 5 26 22 26 11]
 [ 3 14 25 35 12]]
card B
[[12 37  8 32  8]
 [29 22  1 31 13]
 [33 14 19 19 22]
 [ 9 19  8 23 36]
 [ 5  8 39 22 39]]
4番目に出た数字は 9
card A
[[ 2 16 36 12 15]
 [16 39 15 25  0]
 [ 0 36 12 39 26]
 [ 5 26 22 26 11]
 [ 3 14 25 35 12]]
card B
[[12 37  8 32  8]
 [29 22  1 31 13]
 [33 

時間があって遊びたい人用

In [61]:
N=5
a=np.random.randint(1,41,(N,N))
b=np.random.randint(1,41,(N,N))
print('card A')
print(a)
print('card B')
print(b)
x=str(input('AとBどちらのカードにしますか? '))

def rand_ints_nodup(a,b,k):
  num=[]
  while len(num)<k:
    n=random.randint(a,b)
    if not n in num:
      num.append(n)
  return num
list=rand_ints_nodup(1,40,40)
#print(list)

count=0
while count!=-1:
  count+=1
  atari_num=input('1～40の数字を入力してください ')
  atari=list[int(atari_num)-1]
  print(str(count)+'番目に出た数字は '+str(atari))
  a_new=np.where(a==atari,0,a)
  b_new=np.where(b==atari,0,b)
  a=a_new
  b=b_new
  print('card A')
  print(a_new)
  print('card B')
  print(b_new)
  c=np.sum(a_new,axis=0)
  d=np.sum(a_new,axis=1)
  e=np.sum(b_new,axis=0)
  f=np.sum(b_new,axis=1)
  g=np.diag(a_new)
  h=np.diag(np.fliplr(a_new))
  j=np.diag(a_new)
  k=np.diag(np.fliplr(a_new))
  for i in range(N):
    if c[i]==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    elif d[i]==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    elif np.sum(g)==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    elif np.sum(h)==0:
      print('card A BINGOです!')
      count=-1
      y='A'
      break
    if e[i]==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break
    elif f[i]==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break
    elif np.sum(j)==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break
    elif np.sum(k)==0:
      print('card B BINGOです!')
      count=-1
      y='B'
      break

if x==y:
  print('あなたの勝ちです')
else :
  print('あなたの負けです')

card A
[[22 13 31 22 37]
 [21 40 18  7  8]
 [ 7 12 18  9 39]
 [ 3 29 30 11 21]
 [ 6 21 18 31 30]]
card B
[[ 2 37 23  8  3]
 [32 14  3  5 37]
 [37  5 18 29 26]
 [15 13  9 10  1]
 [21 17 17  9 25]]
AとBどちらのカードにしますか? A
1～40の数字を入力してください 1
1番目に出た数字は 9
card A
[[22 13 31 22 37]
 [21 40 18  7  8]
 [ 7 12 18  0 39]
 [ 3 29 30 11 21]
 [ 6 21 18 31 30]]
card B
[[ 2 37 23  8  3]
 [32 14  3  5 37]
 [37  5 18 29 26]
 [15 13  0 10  1]
 [21 17 17  0 25]]
1～40の数字を入力してください 2
2番目に出た数字は 2
card A
[[22 13 31 22 37]
 [21 40 18  7  8]
 [ 7 12 18  0 39]
 [ 3 29 30 11 21]
 [ 6 21 18 31 30]]
card B
[[ 0 37 23  8  3]
 [32 14  3  5 37]
 [37  5 18 29 26]
 [15 13  0 10  1]
 [21 17 17  0 25]]
1～40の数字を入力してください 3
3番目に出た数字は 17
card A
[[22 13 31 22 37]
 [21 40 18  7  8]
 [ 7 12 18  0 39]
 [ 3 29 30 11 21]
 [ 6 21 18 31 30]]
card B
[[ 0 37 23  8  3]
 [32 14  3  5 37]
 [37  5 18 29 26]
 [15 13  0 10  1]
 [21  0  0  0 25]]
1～40の数字を入力してください 4
4番目に出た数字は 19
card A
[[22 13 31 22 37]
 [21 40 18  7  8]
 [ 7 12 18  0 39]
 [ 3 29 30